apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clabernetes
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'oci://ghcr.io/srl-labs/clabernetes'
    targetRevision: ~0.3.3
    chart: clabernetes
  - repoURL: https://github.com/SirHoppington/argo_clab.git
    targetRevision: HEAD
    path: clabernetes/value
  destination:
    server: https://kubernetes.default.svc
    namespace: clabernetes
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=false
    - RespectIgnoreDifferences=true
    - Validate=false
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    managedFieldsManagers:
    - kube-controller-manager
