apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-labs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    # Check Repo settings here
    - pullRequest:
        github:
          owner: SirHoppington
          repo: net_gitops
          tokenRef:
            secretName: pull-request-git
            key: token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "lab-pr-{{ .number }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/SirHoppington/argo_clab.git
        targetRevision: "{{ .head_sha }}"
        path: topology/base
        directory:
          recurse: true
      destination:
        namespace: "lab-pr-{{ .number }}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          # server-side apply added
          - ServerSideApply=true
          - preserveResourcesOnDeletion=false
          - SkipDryRunOnMissingResource=true


      ignoreDifferences:
          - group: ""
            kind: Namespace
            jsonPointers:
            - /metadata/labels