apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-labs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    # Check Repo settings
    - pullRequest:
        github:
          owner: SirHoppington
          repo: argo_clab
          tokenRef:
            secretName: pull-request
            key: token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: lab-pr-{{ .head_sha }}
    spec:
      project: default
      source:
        repoURL: https://github.com/SirHoppington/argo_clab.git
        targetRevision: "{{ .head_sha }}"
        path: .
        directory:
          recurse: true
      destination:
        namespace: lab-pr-{{ .head_sha }}
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
